name: Workflow push
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: récupérer le code
        uses: actions/checkout@v4
      - name: install
        run: npm install
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - name: Upload le résultat du build
        uses: actions/upload-artifact@v4
        with:
          name: mon-site
          path: next/

  exec:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Dowload le projet
        uses: actions/download-artifact@v4
        with:
          path: next/
      - name: affiche
        run: |
          ls next/

